consul_proxy:
    path: /{url}
    defaults:
        _controller: 'ConsulBundle\Controller\ProxyController'
    requirements:
        url: .+

consul_ui:
    path: '/'
    defaults:
        _controller:  FrameworkBundle:Template:template
        template: '@Consul/index.html.twig'
